<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hh_powermail_timeprotect"
 *
 * Auto generated by Extension Builder 2024-01-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['hh_powermail_timeprotect'] = [
    'title' => 'Hauer-Heinrich - Powermail time protection',
    'description' => 'Powermail time protection - for spam prevention.',
    'category' => 'distribution',
    'author' => 'Christian Hackl',
    'author_email' => 'web@hauer-heinrich.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '^12.4.0',
            'fluid_styled_content' => '',
            'powermail' => '',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
    'autoload' => [
        'psr-4' => [
            'HauerHeinrich\\HhPowermailTimeprotect\\' => 'Classes'
        ],
    ],
];
